---
- name: "Scale to {{ ec2cloud_exact_count }} instances"
  local_action:
    module: ec2
    assign_public_ip: "{{ ec2cloud_assign_public_ip }}"
    wait: "{{ ec2cloud_wait }}"
    region: "{{ ec2_region }}"
    vpc_subnet_id: "{{ ec2network_vpc_subnet_id }}"
    group: "{{ ec2security_group_name }}"
    exact_count: "{{ ec2cloud_exact_count }}"
    image: "{{ ec2cloud_image }}"
    instance_type: "{{ ec2cloud_instance_type }}"
    key_name: "{{ ec2security_key_name }}"
    instance_tags: "{{ ec2cloud_instance_tags }}"
    count_tag: "{{ ec2cloud_instance_tags }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2cloud_boot_disk_volume_size }}"
        delete_on_termination: "{{ ec2cloud_boot_disk_delete_on_termination }}"
  register: return_ec2cloud
  notify:
    - Wait for ansible remote access
  tags:
    - scale
    - ec2cloud

- debug: var=return_ec2
  when: ec2_debug

- name: Refresh inventory
  meta: refresh_inventory
  when:
    - test is not defined
