---
- name: "Scale to {{ ec2_exact_count }} instances"
  local_action:
    module: ec2
    region: "{{ ec2_region }}"
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_boot_disk_volume_size }}"
        delete_on_termination: true
    exact_count: "{{ ec2_exact_count }}"
    instance_tags: "{{ ec2_instance_tags }}"
    count_tag: "{{ ec2_instance_tags }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    group: "{{ ec2_security_group }}"
    assign_public_ip: "{{ ec2_assign_public_ip }}"
  register: return_ec2
  notify:
    - Wait for SSH
  tags:
    - scale
    - ec2

- debug: var=return_ec2
  when: ec2_debug

- name: Add hosts to in-memory Inventory Groups
  local_action:
    module: add_host
    name: "{{ item.public_ip }}"
    ansible_host: "{{ item.public_ip }}"
    ansible_user: "{{ ec2_login_username }}"
    ansible_port: "{{ ec2_ssh_port }}"
    ansible_ssh_private_key_file: "{{ ec2_key_dir }}/{{ ec2_key_name }}"
    groups: ec2
    tags: "{{ ec2_instance_tags }}"
  with_items: "{{ return_ec2.tagged_instances }}"
  when: return_ec2.tagged_instances > 0
  tags:
    - scale
    - add_host
