---
- name: Wait for ansible remote access
  wait_for:
    host: "{{ item.public_ip }}"
    port: "{{ ec2cloud_ansible_port }}"
    delay: 30
    timeout: 320
  with_items: "{{ return_ec2cloud.instances }}"
  when:
    - return_ec2cloud.instances > 0
    - ec2cloud_exact_count|int > 0
